"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."

"preserve_hierarchy": true

"files": [
  {
    "source": "/**/lang/en_us.json",
    "translation": "/**/lang/%locale%.json",
    "languages_mapping": {
      "locale": {
        "zh-CN": "zh_cn",
        "zh-HK": "zh_hk",
        "zh-TW": "zh_tw",
        "en-GB": "en_gb",
        "en-US": "en_us",
        "fr": "fr_fr",
        "de": "de_de",
        "id": "id_id",
        "it": "it_it",
        "ja": "ja_jp",
        "pt-PT": "pt_pt",
        "pt-BR": "pt_br",
        "ru": "ru_ru",
        "uk": "uk_ua",
        "nl": "nl_nl",
        "en-PT": "en_pt",
        "en-UD": "en_ud"
      }
    }
  }
]