[versions]
fabric_loom = "1.17-SNAPSHOT"
modpublish = "2.1.1"

minecraft = "26.2"

fabric_loader = "0.19.3"
fabric_api = "0.154.2+26.2"

[plugins]
fabric_loom = { id = "net.fabricmc.fabric-loom", version.ref = "fabric_loom" }
modpublish = { id = "me.modmuss50.mod-publish-plugin", version.ref = "modpublish" }

[libraries]
minecraft = { group = "mojang", name = "minecraft", version.ref = "minecraft" }

fabric_loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric_loader" }
fabric_api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric_api" }
